LMS/Controllers/SatinAlimController.cs
using LMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VeritabanıKatman;

namespace LMS.Controllers
{
    public class SatinAlimController : Controller
    {
        
        private KutuphaneOtomasyonSistemiDBEntities db = new KutuphaneOtomasyonSistemiDBEntities();
        
        // GET: SatinAlim  
        public ActionResult YeniSatinAlim() 
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }
            
            double toplamtutar = 0;
            var gecicisatinalim = db.tbl_SatinAlinanDetay.ToList();
            foreach (var item in gecicisatinalim)
            {
                toplamtutar += (item.adet * item.birimFiyat);
            }

            ViewBag.ToplamTutar = toplamtutar;

            return View(gecicisatinalim);
        }

        [HttpPost]
        public ActionResult UrunEkle(int BID,int adet,float fiyat) 
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var find = db.tbl_SatinAlinanDetay.Where(i => i.id_Kitap == BID).FirstOrDefault();
            if (find == null)
            {
                if (BID > 0 && adet > 0 && fiyat > 0)
                {
                    var yeniurun = new tbl_SatinAlinanDetay()
                    {
                        id_Kitap = BID,
                        adet = adet,
                        birimFiyat = fiyat
                    };

                    db.tbl_SatinAlinanDetay.Add(yeniurun);
                    db.SaveChanges();
                    ViewBag.Message = "Başarıyla eklendi";

                }
            }
            else
            {
                ViewBag.Message = "Bu kitap zaten satın alınmış";
            }
            return RedirectToAction("YeniSatinAlim");
        }

        public ActionResult DeleteConfirm(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var kitap = db.tbl_SatinAlinanDetay.Find(id);
            if (kitap != null)
            {
                db.Entry(kitap).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();
                ViewBag.Message = "Başarıyla silindi";
                return RedirectToAction("YeniSatinAlim");
            }

            ViewBag.Message = "Beklenmeyen bir durum oluştu,iletişime geçin";
            return View("YeniSatinAlim");
        }

        [HttpGet]
        public ActionResult KitapGetir() 
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            List<KitapMV> list = new List<KitapMV>();
            var kitaplist = db.tbl_Kitap.ToList();
            foreach (var item in kitaplist)
            {
                list.Add(new KitapMV { kitapAdi = item.kitapAdi, id_Kitap = item.id_Kitap });
            }

            return Json(new { data = list }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SatinAlimIptal()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var list = db.tbl_SatinAlinanDetay.ToList();
            bool iptaldurumu = false;
            foreach (var item in list)
            {
                db.Entry(item).State = System.Data.Entity.EntityState.Deleted;
                int kayitdurumu = db.SaveChanges();
                if (iptaldurumu == false)
                {
                    if (kayitdurumu > 0)
                    {
                        iptaldurumu = true;
                    }
                }
            }
            if (iptaldurumu == true)
            {
                ViewBag.Message = "Satın alım iptal edildi";
                return RedirectToAction("YeniSatinAlim");
            }
            ViewBag.Message = "Beklenmeyen bir durum oluştu,iletişime geçin";
            return RedirectToAction("YeniSatinAlim");          
        }

        public ActionResult SaticiSec()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var satinalimdetay = db.tbl_SatinAlinanDetay.ToList();
            if (satinalimdetay.Count == 0)
            {
                ViewBag.Message = "Sepet boş";
                return RedirectToAction("YeniSatinAlim");
            }
            var saticilar = db.tbl_Satici.ToList();
            return View(saticilar);
        }

        [HttpPost]
        public ActionResult SatinAlimOnayla(FormCollection collection) 
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            int kullaniciId = Convert.ToInt32(Convert.ToString(Session["id_Kullanici"]));
            int saticiId = 0;
            string[] keys = collection.AllKeys;
            foreach (var name in keys)
            {
                if (name.Contains("name"))
                {
                    string idname = name;
                    string[] valueids = idname.Split(' ');
                    saticiId = Convert.ToInt32(valueids[1]);

                }
            }

            var satinalimdetay = db.tbl_SatinAlinanDetay.ToList();
            double toplamtutar = 0;
            foreach (var item in satinalimdetay)
            {
                toplamtutar = toplamtutar + (item.adet * item.birimFiyat);
            }

            if (toplamtutar == 0)
            {
                ViewBag.Message = "Satın alım sepeti boş";
                return View("YeniSatinAlim");
            }

            var satinAlimHeader = new tbl_SatinAlim();
            satinAlimHeader.id_Satici = saticiId;
            satinAlimHeader.satinAlimTarihi = DateTime.Now;
            satinAlimHeader.satinAlimMiktari = toplamtutar;
            satinAlimHeader.id_Kullanici = kullaniciId;
            db.tbl_SatinAlim.Add(satinAlimHeader);
            db.SaveChanges();

            foreach (var item in satinalimdetay)
            {
                var satindetaylar = new tbl_SatinAlimDetay() 
                {
                    id_Kitap = item.id_Kitap,
                    id_SatinAlim = satinAlimHeader.id_SatinAlim,
                    adet = item.adet,
                    birimFiyat = item.birimFiyat
                };
                db.tbl_SatinAlimDetay.Add(satindetaylar);
                db.SaveChanges();

                var stokguncelle = db.tbl_Kitap.Find(item.id_Kitap);
                stokguncelle.toplamKopya = stokguncelle.toplamKopya + item.adet;
                stokguncelle.fiyat = item.birimFiyat;
                db.Entry(stokguncelle).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

            }

            
            db.tbl_SatinAlinanDetay.ToList().ForEach(x =>
            {
                db.Entry(x).State = System.Data.Entity.EntityState.Deleted;
            });
     

            ViewBag.Message = "Satın alım onaylandı";
            return View("TumSatinAlim");
            
            }


        public ActionResult TumSatinAlim() 
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var list = db.tbl_SatinAlim.ToList();
            return View(list);

        }

        public ActionResult SatinAlimDetayView(int? id) 
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var alimDetay = db.tbl_SatinAlimDetay.Where(b => b.id_SatinAlim == id);
            if (alimDetay == null)
            {
                return HttpNotFound();
            }

            return View(alimDetay);

        }

        }
    }

LMS/Views/SatinAlim/SaticiSec.cshtml
@model IEnumerable<VeritabanıKatman.tbl_Satici>

@{
    ViewBag.Title = "Satın Alımı Bitir";
}

<script src="~/Scripts/jquery-3.4.1.js"></script>

@using (Html.BeginForm("SatinAlimOnayla", "SatinAlim", FormMethod.Post))
{

    <div class="card">
        <div class="card card-flat">
            <div class="card-header">
                @* Buraya Bak *@
            <input type="submit" style="float:right;" value="Satın Alımı Bitir" class="btn btn-success" />
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="dataTable">
                        <thead style="background-color:lightgray;">
                            <tr>

                                <th>
                                    Satıcı
                                </th>
                                <th>
                                    İletişim No
                                </th>

                                <th>
                                    Satıcı Email
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.adi)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.iletisimNo)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.email)
                                    </td>
                                    <td>
                                        <input type="checkbox" name="name @item.id_Satici" class="chb" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {

        $(".chb").change(function (event) {
            $(".chb").prop('checked', false);
            $(this).prop('checked', true);

        });
    });
</script>

LMS/Views/SatinAlim/SatinAlimDetayView.cshtml
@model IEnumerable<VeritabanıKatman.tbl_SatinAlimDetay>

@{
    ViewBag.Title = "Satın Alım Detay";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tüm Satın Alımlar</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.tbl_Kitap.kitapBaslik)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.adet)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.birimFiyat)
                        </th>
                        <th>
                            Kitap Tutarı
                        </th>

                        <th></th>
                    </tr>
                <thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Kitap.kitapBaslik)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.adet)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.birimFiyat)
                            </td>
                            <td>
                                @(string.Format("{0:0}", Math.Truncate(item.adet * item.birimFiyat * 10) / 10))
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

LMS/Views/SatinAlim/TumSatinAlim.cshtml
@model IEnumerable<VeritabanıKatman.tbl_SatinAlim>

@{
    ViewBag.Title = "Tüm Satın Alım";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tüm Satın Alımlar</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Satıcı Adı
                        </th>
                        <th>
                            Alım Tarihi
                        </th>
                        <th>
                            Alım Miktarı
                        </th>
                        <th>
                            Kullanıcı
                        </th>
                        <th>Eylemler</th>
                    </tr>
                <thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Satici.adi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.satinAlimTarihi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.satinAlimMiktari)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Kullanici.kullaniciAdi)
                            </td>
                            <td>
                                @Html.ActionLink("Detaylar", "SatinAlimDetayView", new { id = item.id_SatinAlim }, new { @class = "btn btn-info" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
 

LMS/Views/SatinAlim/YeniSatinAlim.cshtml
@model IEnumerable<VeritabanıKatman.tbl_SatinAlinanDetay>

@{
    ViewBag.Title = "Yeni Satın Alım";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>

@using (Html.BeginForm("UrunEkle", "SatinAlim", FormMethod.Post, null))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <h4>Satın Alım Detayları</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label class="control-label col-md-2">Kitap Seç</label>
        <div class="col-md-6">
            <select class="form-control" id="BID" name="BID" required></select>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Adet</label>
        <div class="col-md-6">
            <input type="number" class="form-control" id="adet" name="adet" placeholder="Adet giriniz.." required />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Birim Fiyat</label>
        <div class="col-md-6">
            <input type="number" class="form-control" id="fiyat" step=".01" name="fiyat" placeholder="Birim fiyat giriniz..." required />
        </div>

        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Urun Ekle" class="btn btn-success" />
            </div>
        </div>        
      </div>
    </div>
    }


    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Satın Alım Listesi</h6>
            <h3 class="text-danger">@ViewBag.Message</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                Kitap
                            </th>
                            <th>
                                Satın Alım Adedi
                            </th>
                            <th>
                                Birim Fiyat
                            </th>
                            <th>
                                Ürün Tutarı
                            </th>
                            <th>Eylemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.tbl_Kitap.kitapAdi)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.adet)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.birimFiyat)
                                </td>
                                <td>
                                    @(string.Format("{0:0}", Math.Truncate(item.adet * item.birimFiyat * 10) / 10))
                                </td>
                                <td>
                                    @Html.ActionLink("Sil", "DeleteConfirm", new { id = item.id_SatinAlinan }, new { @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>

                            <td></td>
                            <td></td>

                            <td style="background-color:black; color:white;">Toplam Tutar</td>
                            <td style="background-color:black; color:white;">
                                @(string.Format("{0:0}", Math.Truncate(ViewBag.ToplamTutar * 10) / 10)) TL
                            </td>
                            <td></td>

                        </tr>
                    </tfoot>
                </table>
                <div style="margin-top:20px; float:right">
                    @Html.ActionLink("İleri", "SaticiSec", null, new { @class = "btn btn-success", style = "padding:20px;" })
                    @Html.ActionLink("İptal", "SatinAlimIptal", null, new { @class = "btn btn-danger", style = "padding:20px;" })
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
    $(document).ready(function () {


        $.ajax({
            url: '@Url.Action("KitapGetir", "SatinAlim")',
            type: 'GET',
            data: "{}",
            success: function (response) {
                for (var i = 0; i < response.data.length; i++)
                {
                    $('#BID').append("<option value=" + response.data[i].id_Kitap + ">" + response.data[i].kitapAdi + "</option>");
                }
            },
            error: function () {
            }
        });
    });
    </script>