LMS/Controllers/KitapDonusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VeritabanıKatman;

namespace LMS.Controllers
{
    public class KitapDonusController : Controller
    {
        private KutuphaneOtomasyonSistemiDBEntities db = new KutuphaneOtomasyonSistemiDBEntities();

        // GET: KitapDonus
        public ActionResult Index()
        {
            var tbl_KitapDonus = db.tbl_KitapDonus.Include(t => t.tbl_Calisan).Include(t => t.tbl_Kullanici).Include(t => t.tbl_Kullanici1);
            return View(tbl_KitapDonus.ToList());
        }

        // GET: KitapDonus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_KitapDonus tbl_KitapDonus = db.tbl_KitapDonus.Find(id);
            if (tbl_KitapDonus == null)
            {
                return HttpNotFound();
            }
            return View(tbl_KitapDonus);
        }

        // GET: KitapDonus/Create
        public ActionResult Create()
        {
            ViewBag.id_Calisan = new SelectList(db.tbl_Calisan, "id_Calisan", "tamAdi");
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi");
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi");
            return View();
        }

        // POST: KitapDonus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_KitapDonus,id_Kullanici,id_Kitap,id_Calisan,verilisTarihi,donusTarihi,gecerliTarih")] tbl_KitapDonus tbl_KitapDonus)
        {
            if (ModelState.IsValid)
            {
                db.tbl_KitapDonus.Add(tbl_KitapDonus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_Calisan = new SelectList(db.tbl_Calisan, "id_Calisan", "tamAdi", tbl_KitapDonus.id_Calisan);
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi", tbl_KitapDonus.id_Kullanici);
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi", tbl_KitapDonus.id_Kullanici);
            return View(tbl_KitapDonus);
        }

        // GET: KitapDonus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_KitapDonus tbl_KitapDonus = db.tbl_KitapDonus.Find(id);
            if (tbl_KitapDonus == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_Calisan = new SelectList(db.tbl_Calisan, "id_Calisan", "tamAdi", tbl_KitapDonus.id_Calisan);
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi", tbl_KitapDonus.id_Kullanici);
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi", tbl_KitapDonus.id_Kullanici);
            return View(tbl_KitapDonus);
        }

        // POST: KitapDonus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_KitapDonus,id_Kullanici,id_Kitap,id_Calisan,verilisTarihi,donusTarihi,gecerliTarih")] tbl_KitapDonus tbl_KitapDonus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_KitapDonus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_Calisan = new SelectList(db.tbl_Calisan, "id_Calisan", "tamAdi", tbl_KitapDonus.id_Calisan);
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi", tbl_KitapDonus.id_Kullanici);
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi", tbl_KitapDonus.id_Kullanici);
            return View(tbl_KitapDonus);
        }

        // GET: KitapDonus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_KitapDonus tbl_KitapDonus = db.tbl_KitapDonus.Find(id);
            if (tbl_KitapDonus == null)
            {
                return HttpNotFound();
            }
            return View(tbl_KitapDonus);
        }

        // POST: KitapDonus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_KitapDonus tbl_KitapDonus = db.tbl_KitapDonus.Find(id);
            db.tbl_KitapDonus.Remove(tbl_KitapDonus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LMS/Controllers/VerilenKitapController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VeritabanıKatman;

namespace LMS.Controllers
{
    public class VerilenKitapController : Controller
    {
        private KutuphaneOtomasyonSistemiDBEntities db = new KutuphaneOtomasyonSistemiDBEntities();

        // GET: VerilenKitap
        public ActionResult VerilenKitap()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var tbl_VerilenKitap = db.tbl_VerilenKitap.Include(t => t.tbl_Calisan).Include(t => t.tbl_Kitap).Include(t => t.tbl_Kitap1).Include(t => t.tbl_Kitap2).Include(t => t.tbl_Kullanici).Include(t => t.tbl_Kullanici1).Where(b => b.durum == true && b.rezerveKopya == false);
            return View(tbl_VerilenKitap.ToList());
        }

        public ActionResult RezerveKitap()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var tbl_VerilenKitap = db.tbl_VerilenKitap.Include(t => t.tbl_Calisan).Include(t => t.tbl_Kitap).Include(t => t.tbl_Kitap1).Include(t => t.tbl_Kitap2).Include(t => t.tbl_Kullanici).Include(t => t.tbl_Kullanici1).Where(b => b.durum == false && b.rezerveKopya == true && b.donusTarihi > DateTime.Now);
            return View(tbl_VerilenKitap.ToList());
        }

        public ActionResult DonusBekleyenKitap()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            List<tbl_VerilenKitap> list = new List<tbl_VerilenKitap>();
            var tbl_VerilenKitap = db.tbl_VerilenKitap.Where(b => b.durum == true && b.rezerveKopya == true).ToList();
            foreach (var item in tbl_VerilenKitap)
            {

                var donustarihi = item.donusTarihi;
                int gunsayisi = (donustarihi - DateTime.Now).Days;
                if (gunsayisi <= 3)
                {
                    list.Add(new tbl_VerilenKitap
                    {
                        id_Kitap = item.id_Kitap,
                        tbl_Kitap = item.tbl_Kitap,
                        aciklama = item.aciklama,
                        id_Calisan = item.id_Calisan,
                        tbl_Calisan = item.tbl_Calisan,
                        id_VerilenKitap = item.id_VerilenKitap,
                        verilenKopya = item.verilenKopya,
                        verilisTarihi = item.verilisTarihi,
                        rezerveKopya = item.rezerveKopya,
                        donusTarihi = item.donusTarihi,
                        durum = item.durum,
                        id_Kullanici = item.id_Kullanici,
                        tbl_Kullanici = item.tbl_Kullanici,
                    });
                }
            }

               return View(list.ToList());
        }

       

        // GET: VerilenKitap/Details/5
        public ActionResult Details(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_VerilenKitap tbl_VerilenKitap = db.tbl_VerilenKitap.Find(id);
            if (tbl_VerilenKitap == null)
            {
                return HttpNotFound();
            }
            return View(tbl_VerilenKitap);
        }

        // GET: VerilenKitap/Create
        public ActionResult Create()
        {
            ViewBag.id_Calisan = new SelectList(db.tbl_Calisan, "id_Calisan", "tamAdi","0");
            ViewBag.id_Kitap = new SelectList(db.tbl_Kitap, "id_Kitap", "kitapBaslik","0");
            ViewBag.id_Kitap = new SelectList(db.tbl_Kitap, "id_Kitap", "kitapBaslik","0");
            ViewBag.id_Kitap = new SelectList(db.tbl_Kitap, "id_Kitap", "kitapBaslik","0");
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi","0");
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi","0");
            return View();
        }

        // POST: VerilenKitap/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tbl_VerilenKitap tbl_VerilenKitap)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }
            
            int kullaniciId = Convert.ToInt32(Convert.ToString(Session["id_Kullanici"]));
            tbl_VerilenKitap.id_Kullanici = kullaniciId;
            
            if (ModelState.IsValid)
            {
                var find = db.tbl_VerilenKitap.Where(b => b.donusTarihi >= DateTime.Now && b.id_Kitap == tbl_VerilenKitap.id_Kitap && (b.durum == true || b.rezerveKopya == true)).ToList();
                int verilenkitapsayi = 0;
                
                foreach (var item in find)
                {
                    verilenkitapsayi = verilenkitapsayi + item.verilenKopya;
                }

                var kitapstok = db.tbl_Kitap.Where(b => b.id_Kitap == tbl_VerilenKitap.id_Kitap).FirstOrDefault();
                if ((verilenkitapsayi == kitapstok.toplamKopya) || (verilenkitapsayi + tbl_VerilenKitap.verilenKopya > kitapstok.toplamKopya))
                {
                    ViewBag.Message = "Stok boş";
                    return View(tbl_VerilenKitap);
                }


                db.tbl_VerilenKitap.Add(tbl_VerilenKitap);
                db.SaveChanges();
                ViewBag.Message = "Kitap başarıyla verildi";
                return RedirectToAction("Index");
            }

            ViewBag.id_Calisan = new SelectList(db.tbl_Calisan, "id_Calisan", "tamAdi", tbl_VerilenKitap.id_Calisan);
            ViewBag.id_Kitap = new SelectList(db.tbl_Kitap, "id_Kitap", "kitapBaslik", tbl_VerilenKitap.id_Kitap);
            ViewBag.id_Kitap = new SelectList(db.tbl_Kitap, "id_Kitap", "kitapBaslik", tbl_VerilenKitap.id_Kitap);
            ViewBag.id_Kitap = new SelectList(db.tbl_Kitap, "id_Kitap", "kitapBaslik", tbl_VerilenKitap.id_Kitap);
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi", tbl_VerilenKitap.id_Kullanici);
            ViewBag.id_Kullanici = new SelectList(db.tbl_Kullanici, "id_Kullanici", "kullaniciAdi", tbl_VerilenKitap.id_Kullanici);
            return View(tbl_VerilenKitap);
        }

        public ActionResult KitapDonus(int? id) 
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["id_Kullanici"])))
            {
                return RedirectToAction("Login", "Home");
            }

            int kulllaniciId = Convert.ToInt32(Convert.ToInt32(Convert.ToString(Session["id_Kullanici"])));

            var kitap = db.tbl_VerilenKitap.Find(id);
            int ceza = 0;
            var donustarihi = kitap.donusTarihi;
            int gunsayisi = (DateTime.Now - donustarihi).Days;
            if (gunsayisi > 0)
            {
                ceza = 20 * gunsayisi;
            }
            if (kitap.durum == true && kitap.rezerveKopya == false)
            {
                var kitapDonus = new tbl_KitapDonus()
                {
                    id_Kitap = kitap.id_Kitap,
                    gecerliTarih = DateTime.Now,
                    id_Calisan = kitap.id_Calisan,
                    verilisTarihi = kitap.verilisTarihi,
                    donusTarihi = kitap.donusTarihi,
                    id_Kullanici = kulllaniciId,
                };
                db.tbl_KitapDonus.Add(kitapDonus);
                db.SaveChanges();
            }

            kitap.durum = false;
            kitap.rezerveKopya = false;
            db.Entry(kitap).State = EntityState.Modified;
            db.SaveChanges();

            if (ceza > 0)
            {
                var cezaekle = new tbl_KitapCeza()
                {
                    id_Kitap = kitap.id_Kitap,
                    id_Calisan = kitap.id_Calisan,
                    cezaMiktar = ceza,
                    cezaTarihi = DateTime.Now,
                    kalanGun = gunsayisi,
                    kalanMiktar = 0,
                    id_Kullanici = kulllaniciId,
                };
                db.tbl_KitapCeza.Add(cezaekle);
                db.SaveChanges();
            }
            return RedirectToAction("VerilenKitap");
        }


      
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LMS/Views/VerilenKitap/Create.cshtml
@model VeritabanıKatman.tbl_VerilenKitap

@{
    ViewBag.Title = "Kitap Bilgileri";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 class="text-danger">@ViewBag.Message</h4>
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.id_Calisan, "Çalışan Seçin", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_Calisan", null, "---Çalışan---", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.id_Calisan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_Kitap, "Kitap Seçin", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_Kitap", null, "---Kitap---", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.id_Kitap, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.verilenKopya, "Verilen Kopya", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.verilenKopya, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.verilenKopya, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.verilisTarihi, "Veriliş Tarihi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.verilisTarihi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.verilisTarihi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.donusTarihi, "Dönüş Tarihi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.donusTarihi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.donusTarihi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.durum, "Veriliş Durumu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.durum)
                @Html.ValidationMessageFor(model => model.durum, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.rezerveKopya, "Rezerve Durumu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.rezerveKopya)
                @Html.ValidationMessageFor(model => model.rezerveKopya, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.aciklama, "Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.aciklama, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.aciklama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kitap Ver" class="btn btn-success" />
            @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>
}

LMS/Views/VerilenKitap/Delete.cshtml
@model VeritabanıKatman.tbl_VerilenKitap

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_VerilenKitap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.verilenKopya)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.verilenKopya)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.verilisTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.verilisTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.donusTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donusTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rezerveKopya)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rezerveKopya)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_Calisan.tamAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_Calisan.tamAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_Kitap.kitapBaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_Kitap.kitapBaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_Kitap1.kitapBaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_Kitap1.kitapBaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_Kitap2.kitapBaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_Kitap2.kitapBaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_Kullanici.kullaniciAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_Kullanici.kullaniciAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_Kullanici1.kullaniciAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_Kullanici1.kullaniciAdi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LMS/Views/VerilenKitap/RezerveKitap.cshtml
@model IEnumerable<VeritabanıKatman.tbl_VerilenKitap>

@{
    ViewBag.Title = "Rezerve Kitaplar";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Rezerve Kitaplar</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Kitap Başlığı
                        </th>
                        <th>
                            Çalışan
                        </th>
                        <th>
                            Verilen Kopya
                        </th>
                        <th>
                            Veriliş Tarihi
                        </th>
                        <th>
                            Dönüş Tarihi
                        </th>
                        <th>
                            Durum
                        </th>
                        <th>
                            Rezerve Kopya
                        </th>
                        <th>
                            Açıklama
                        </th>
                        <th>
                            Kullanıcı
                        </th>
                        <th>Eylemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Kitap.kitapBaslik)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Calisan.tamAdi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.verilenKopya)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.verilisTarihi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.donusTarihi)
                            </td>
                            <td>
                                <p class="text-success" style="font:bold">Rezerve</p>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.rezerveKopya)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.aciklama)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Kullanici.kullaniciAdi)
                            </td>
                            <td>
                                @Html.ActionLink("Kitap Dönüş", "KitapDonus", new { id = item.id_VerilenKitap }, new {@class="btn btn-primary"}) 
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            </div>
            </div>
        </div>

LMS/Views/VerilenKitap/VerilenKitap.cshtml
@model IEnumerable<VeritabanıKatman.tbl_VerilenKitap>

@{
    ViewBag.Title = "Verilen Kitaplar";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Verilen Kitaplar</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Kitap Başlığı
                        </th>
                        <th>
                            Çalışan
                        </th>
                        <th>
                            Verilen Kopya
                        </th>
                        <th>
                            Veriliş Tarihi
                        </th>
                        <th>
                            Dönüş Tarihi
                        </th>
                        <th>
                            Durum
                        </th>
                        <th>
                            Rezerve Kopya
                        </th>
                        <th>
                            Açıklama
                        </th>
                        <th>
                            Kullanıcı
                        </th>
                        <th>Eylemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Kitap.kitapBaslik)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Calisan.tamAdi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.verilenKopya)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.verilisTarihi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.donusTarihi)
                            </td>
                            <td>
                                <p class="text-success" style="font:bold">Durum</p>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.rezerveKopya)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.aciklama)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_Kullanici.kullaniciAdi)
                            </td>
                            <td>
                                @Html.ActionLink("Kitap Dönüş", "KitapDonus", new { id = item.id_VerilenKitap }, new { @class = "btn btn-primary" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            </div>
            </div>
            </div>
        